runtime: python37

handlers:
  - url: /
    static_files: webapp/index.html
    upload: webapp/index.html

  - url: /api/.*
    script: auto

  - url: /docs
    static_dir: docs

  - url: /(.*)
    static_files: webapp/\1
    upload: webapp/(.*)
